version: "3"

services:
  # core.aspnet:
  #   image: mcr.microsoft.com/dotnet/core/aspnet
  #   container_name: core-aspnet

  # core.runtime:
  #   image: mcr.microsoft.com/dotnet/core/runtime
  #   container_name: core-runtime
    
  sqlserver.database:
    image: microsoft/mssql-server-linux:latest
    container_name: sql-server
    environment:
      SA_PASSWORD: "meus-jogos@pwd"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"

  meusjogos.api:
    image: meus-jogos-api
    container_name: meus-jogos-api
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver.database

  meusjogos.front:
    image: meus-jogos-front
    container_name: meus-jogos-front
    ports:
      - "1234:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - meusjogos.api
