version: "3"

services:
  sql-server:
    image: microsoft/mssql-server-linux:latest
    container_name: sql-server
    environment:
      SA_PASSWORD: "Meus-jogos@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"

  meusjogos.api:
    image: meus-jogos-api
    container_name: meus-jogos-api
    ports:
      - "5000:80"
    depends_on:
      - sql-server

  meusjogos.front:
    image: meus-jogos-front
    container_name: meus-jogos-front
    ports:
      - "44324:80"
    depends_on:
      - meusjogos.api
